import { StyleSheet } from "@react-pdf/renderer";

export const brand = {
  orange: "#F26B21",
  navy: "#12253A",
  ink: "#1B1F24",
  slate: "#5A6672",
  mist: "#E7EAED",
  paper: "#F7F7F5",
  white: "#FFFFFF",
};

export const styles = StyleSheet.create({
  page: {
    paddingTop: 36,
    paddingBottom: 56,
    paddingHorizontal: 40,
    fontSize: 9.5,
    fontFamily: "Helvetica",
    color: brand.ink,
    lineHeight: 1.5,
  },
  headerRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between" },
  logo: { width: 96 },
  headerRight: { alignItems: "flex-end" },
  eyebrow: { fontSize: 7.5, letterSpacing: 1.2, color: brand.orange, fontFamily: "Helvetica-Bold" },
  title: { fontSize: 19, color: brand.navy, fontFamily: "Helvetica-Bold", marginTop: 6 },
  metaLine: { fontSize: 8.5, color: brand.slate },

  /* Customer-facing proposal */
  clientPage: {
    paddingTop: 40,
    paddingBottom: 96,
    paddingHorizontal: 44,
    fontSize: 9.5,
    fontFamily: "Helvetica",
    color: brand.ink,
    lineHeight: 1.5,
  },
  clientHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 8,
  },
  clientIdentity: { flexDirection: "row", alignItems: "center", maxWidth: 360 },
  clientLogo: { width: 40, height: 40, objectFit: "contain", marginRight: 12 },
  clientName: { fontSize: 22, lineHeight: 1.15, color: brand.navy, fontFamily: "Helvetica-Bold" },
  providerBlock: { alignItems: "flex-end" },
  providerLogo: { width: 72, height: 24, objectFit: "contain", objectPosition: "right", marginBottom: 6 },
  providerName: { fontSize: 10, color: brand.navy, fontFamily: "Helvetica-Bold", marginBottom: 6 },
  rule: { borderBottomWidth: 0.75, borderBottomColor: brand.mist, marginTop: 14 },
  investmentEyebrow: {
    marginTop: 18,
    fontSize: 7,
    letterSpacing: 1.2,
    color: brand.slate,
    fontFamily: "Helvetica-Bold",
  },
  tierTitle: { fontSize: 17, color: brand.navy, fontFamily: "Helvetica-Bold", marginTop: 2 },
  investmentCard: {
    marginTop: 8,
    flexDirection: "row",
    borderWidth: 0.75,
    borderColor: brand.mist,
    borderTopWidth: 2,
    borderTopColor: brand.navy,
  },
  rateCell: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRightWidth: 0.75,
    borderRightColor: brand.mist,
    minWidth: 150,
  },
  rateLine: { flexDirection: "row", alignItems: "baseline", marginTop: 2 },
  rateValue: { fontSize: 26, lineHeight: 1.1, color: brand.navy, fontFamily: "Helvetica-Bold" },
  rateUnit: { fontSize: 10, color: brand.slate },
  ratePerUser: { fontSize: 8.5, fontFamily: "Helvetica-Bold", marginTop: 4 },
  countsCell: { flexDirection: "row", paddingVertical: 12, paddingHorizontal: 8 },
  countCell: { paddingHorizontal: 12, paddingTop: 12 },
  countValue: { fontSize: 13, color: brand.navy, fontFamily: "Helvetica-Bold" },
  bundleNote: { marginTop: 6, fontSize: 8.5, color: brand.slate },
  includedIntro: { fontSize: 8.5, color: brand.slate, marginBottom: 6 },
  groupGrid: { flexDirection: "row", flexWrap: "wrap" },
  groupCell: { width: "50%", paddingRight: 24, marginTop: 12 },
  groupTitle: {
    fontSize: 10,
    color: brand.navy,
    fontFamily: "Helvetica-Bold",
    borderBottomWidth: 1.5,
    borderBottomColor: brand.orange,
    paddingBottom: 3,
    marginBottom: 6,
    alignSelf: "flex-start",
  },
  bulletRow: { flexDirection: "row", alignItems: "center", paddingVertical: 2.5 },
  bullet: { width: 3.5, height: 3.5, borderRadius: 2, marginRight: 8 },
  bulletText: { fontSize: 9 },
  nextStep: {
    marginTop: 24,
    backgroundColor: brand.paper,
    borderLeftWidth: 2.5,
    paddingVertical: 8,
    paddingHorizontal: 12,
    fontSize: 9,
  },
  nextStepLabel: { fontFamily: "Helvetica-Bold", color: brand.navy },
  clientFooter: {
    position: "absolute",
    bottom: 30,
    left: 44,
    right: 44,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    borderTopWidth: 0.75,
    borderTopColor: brand.mist,
    paddingTop: 10,
    fontSize: 7,
    color: brand.slate,
    lineHeight: 1.45,
  },
  clientFooterLeft: { width: "42%" },
  clientFooterRight: { width: "52%", textAlign: "right" },
  footerContact: { fontSize: 7.5, color: brand.slate, marginTop: 2 },
  footerContactName: { fontFamily: "Helvetica-Bold", color: brand.ink },
  confidential: {
    marginTop: 14,
    backgroundColor: brand.navy,
    color: brand.white,
    paddingVertical: 5,
    paddingHorizontal: 10,
    fontSize: 7.5,
    letterSpacing: 1.1,
    fontFamily: "Helvetica-Bold",
    textAlign: "center",
  },
  approvalBlock: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: brand.orange,
    backgroundColor: "#FDF1EA",
    padding: 10,
  },
  approvalTitle: { fontFamily: "Helvetica-Bold", color: "#C4520F", fontSize: 10 },
  timelineRow: {
    marginTop: 6,
    borderLeftWidth: 2,
    borderLeftColor: brand.orange,
    paddingLeft: 8,
  },
  section: { marginTop: 18 },
  sectionTitle: {
    fontSize: 8,
    letterSpacing: 1.1,
    color: brand.slate,
    fontFamily: "Helvetica-Bold",
    borderBottomWidth: 1,
    borderBottomColor: brand.navy,
    paddingBottom: 4,
    marginBottom: 8,
  },
  metaGrid: { flexDirection: "row", flexWrap: "wrap", marginTop: 14 },
  metaCell: { width: "25%", paddingVertical: 6, paddingRight: 8 },
  metaLabel: { fontSize: 7.5, letterSpacing: 0.8, color: brand.slate, fontFamily: "Helvetica-Bold" },
  metaValue: { fontSize: 11, color: brand.navy, fontFamily: "Helvetica-Bold" },
  row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 3 },
  rowMuted: { color: brand.slate },
  rowTotal: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: brand.mist,
    marginTop: 4,
    paddingTop: 5,
    fontFamily: "Helvetica-Bold",
    color: brand.navy,
  },
  highlight: {
    marginTop: 12,
    backgroundColor: brand.navy,
    padding: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  highlightLabel: { color: brand.mist, fontSize: 8, letterSpacing: 1.1, fontFamily: "Helvetica-Bold" },
  highlightValue: { color: brand.white, fontSize: 24, fontFamily: "Helvetica-Bold" },
  highlightSub: { color: brand.orange, fontSize: 9.5, fontFamily: "Helvetica-Bold" },
  table: { marginTop: 4 },
  th: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: brand.navy,
    paddingBottom: 4,
    fontSize: 7.5,
    letterSpacing: 0.8,
    color: brand.slate,
    fontFamily: "Helvetica-Bold",
  },
  td: { flexDirection: "row", borderBottomWidth: 0.5, borderBottomColor: brand.mist, paddingVertical: 4 },
  notes: { backgroundColor: brand.paper, padding: 10, marginTop: 4, color: brand.ink },
  stamp: {
    position: "absolute",
    bottom: 22,
    left: 40,
    right: 40,
    borderTopWidth: 1,
    borderTopColor: brand.mist,
    paddingTop: 6,
    fontSize: 7,
    color: brand.slate,
    lineHeight: 1.4,
  },
  watermark: {
    position: "absolute",
    top: 320,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 44,
    color: "#F26B21",
    opacity: 0.12,
    fontFamily: "Helvetica-Bold",
  },
});
