import { StyleSheet } from "@react-pdf/renderer";

export const brand = {
  orange: "#F26B21",
  navy: "#12253A",
  ink: "#1B1F24",
  slate: "#5A6672",
  mist: "#E7EAED",
  paper: "#F7F7F5",
  white: "#FFFFFF",
};

export const styles = StyleSheet.create({
  page: {
    paddingTop: 36,
    paddingBottom: 56,
    paddingHorizontal: 40,
    fontSize: 9.5,
    fontFamily: "Helvetica",
    color: brand.ink,
    lineHeight: 1.5,
  },
  headerRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between" },
  logo: { width: 96 },
  headerRight: { alignItems: "flex-end" },
  eyebrow: { fontSize: 7.5, letterSpacing: 1.2, color: brand.orange, fontFamily: "Helvetica-Bold" },
  title: { fontSize: 19, color: brand.navy, fontFamily: "Helvetica-Bold", marginTop: 6 },
  metaLine: { fontSize: 8.5, color: brand.slate },
  confidential: {
    marginTop: 14,
    backgroundColor: brand.navy,
    color: brand.white,
    paddingVertical: 5,
    paddingHorizontal: 10,
    fontSize: 7.5,
    letterSpacing: 1.1,
    fontFamily: "Helvetica-Bold",
    textAlign: "center",
  },
  approvalBlock: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: brand.orange,
    backgroundColor: "#FDF1EA",
    padding: 10,
  },
  approvalTitle: { fontFamily: "Helvetica-Bold", color: "#C4520F", fontSize: 10 },
  section: { marginTop: 18 },
  sectionTitle: {
    fontSize: 8,
    letterSpacing: 1.1,
    color: brand.slate,
    fontFamily: "Helvetica-Bold",
    borderBottomWidth: 1,
    borderBottomColor: brand.navy,
    paddingBottom: 4,
    marginBottom: 8,
  },
  metaGrid: { flexDirection: "row", flexWrap: "wrap", marginTop: 14 },
  metaCell: { width: "25%", paddingVertical: 6, paddingRight: 8 },
  metaLabel: { fontSize: 7.5, letterSpacing: 0.8, color: brand.slate, fontFamily: "Helvetica-Bold" },
  metaValue: { fontSize: 11, color: brand.navy, fontFamily: "Helvetica-Bold" },
  row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 3 },
  rowMuted: { color: brand.slate },
  rowTotal: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: brand.mist,
    marginTop: 4,
    paddingTop: 5,
    fontFamily: "Helvetica-Bold",
    color: brand.navy,
  },
  highlight: {
    marginTop: 12,
    backgroundColor: brand.navy,
    padding: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  highlightLabel: { color: brand.mist, fontSize: 8, letterSpacing: 1.1, fontFamily: "Helvetica-Bold" },
  highlightValue: { color: brand.white, fontSize: 24, fontFamily: "Helvetica-Bold" },
  highlightSub: { color: brand.orange, fontSize: 9.5, fontFamily: "Helvetica-Bold" },
  table: { marginTop: 4 },
  th: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: brand.navy,
    paddingBottom: 4,
    fontSize: 7.5,
    letterSpacing: 0.8,
    color: brand.slate,
    fontFamily: "Helvetica-Bold",
  },
  td: { flexDirection: "row", borderBottomWidth: 0.5, borderBottomColor: brand.mist, paddingVertical: 4 },
  notes: { backgroundColor: brand.paper, padding: 10, marginTop: 4, color: brand.ink },
  stamp: {
    position: "absolute",
    bottom: 22,
    left: 40,
    right: 40,
    borderTopWidth: 1,
    borderTopColor: brand.mist,
    paddingTop: 6,
    fontSize: 7,
    color: brand.slate,
    lineHeight: 1.4,
  },
  watermark: {
    position: "absolute",
    top: 320,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 44,
    color: "#F26B21",
    opacity: 0.12,
    fontFamily: "Helvetica-Bold",
  },
});
